FROM atendai/evolution-api:v2.2.3

ENV AUTHENTICATION_API_KEY=baz2026secret
ENV SERVER_PORT=8080
ENV DATABASE_ENABLED=false
ENV REDIS_ENABLED=false
ENV LOG_LEVEL=ERROR
ENV LOG_COLOR=true

EXPOSE 8080
